fragment postDetail on BlogPost {
  id
  title
  content(format: HTML)
  publish_date
  slug
  cursor
  author_id
}

query GetPost($id: ID!) {
  blog_post(id: $id) {
    ...postDetail
  }
}

query GetPostEdits($id: ID!) {
  blog_post(id: $id) {
    edits {
      id
      date
    }
  }
}

query GetPostForEdit($id: ID!) {
  blog_post(id: $id) {
    title
    content(format: MARKDOWN)
    publish_date
    slug
  }
}

query GetPosts($cursor: String, $before: Int!, $after: Int!) {
  blog_posts(
    pager: { after: $cursor, first: $after, before: $cursor, last: $before }
  ) {
    beforeEdges {
      node {
        ...postDetail
      }
      cursor
    }
    afterEdges {
      node {
        ...postDetail
      }
      cursor
    }
  }
}

mutation CreatePost($input: CreateBlogPostInput!) {
  post: create_blog_post(input: $input) {
    ...postDetail
  }
}

mutation EditPost($id: ID!, $input: UpdateBlogPostInput!) {
  post: update_blog_post(id: $id, input: $input) {
    ...postDetail
  }
}

mutation DeletePost($id: ID!) {
  id: delete_blog_post(id: $id)
}
